### ISSUE TITLE
getProperties 方法报错

### ISSUE THREAD

**Issue by iOShuyang** [869413421/hyperf-mall#2]
正在处理索引 products
索引不存在，准备创建
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636

**Comment by 869413421** [comment]
你的es什么版本





| |
黄彦铭
|
|
邮箱：13528685024@163.com
|

签名由 网易邮箱大师 定制

在2020年06月18日 15:31，HuYang 写道：

正在处理索引 products
索引不存在，准备创建
PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636

**Comment by iOShuyang** [comment]
> 你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

6.8.7的

**Comment by 869413421** [comment]
需要7.0以上的版本，因为7.0去除了type的概念，你使用6.8的需要手动设置type，所以代码会报错。










在 2020-06-18 15:36:09，"HuYang" <notifications@github.com> 写道：

你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

6.8.7的

**Comment by iOShuyang** [comment]
> 需要7.0以上的版本，因为7.0去除了type的概念，你使用6.8的需要手动设置type，所以代码会报错。 在 2020-06-18 15:36:09，"HuYang" <notifications@github.com> 写道： 你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 6.8.7的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问如何手动设置type？

**Comment by iOShuyang** [comment]
> 你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

{
  "name" : "g6zRt-N",
  "cluster_name" : "elasticsearch_huyang",
  "cluster_uuid" : "dvOrOpJXTlqGZ4-OLcajWg",
  "version" : {
    "number" : "6.8.7",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "c63e621",
    "build_date" : "2020-02-26T14:38:01.193138Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.2",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by 869413421** [comment]
需要修改迁移命令的代码，修改下创建索引和重建索引方法就可以了




| |
黄彦铭
|
|
邮箱：13528685024@163.com
|

签名由 网易邮箱大师 定制

在2020年06月18日 15:46，HuYang 写道：

你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

{
"name" : "g6zRt-N",
"cluster_name" : "elasticsearch_huyang",
"cluster_uuid" : "dvOrOpJXTlqGZ4-OLcajWg",
"version" : {
"number" : "6.8.7",
"build_flavor" : "oss",
"build_type" : "tar",
"build_hash" : "c63e621",
"build_date" : "2020-02-26T14:38:01.193138Z",
"build_snapshot" : false,
"lucene_version" : "7.7.2",
"minimum_wire_compatibility_version" : "5.6.0",
"minimum_index_compatibility_version" : "5.0.0"
},
"tagline" : "You Know, for Search"
}

**Comment by 869413421** [comment]
url :{{esHost}}products/_mapping


josn :{
  "properties": {
    "type": { "type": "keyword" } ,
    "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, 
    "long_title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, 
    "category_id": { "type": "integer" },
    "category": { "type": "keyword" },
    "category_path": { "type": "keyword" },
    "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" },
    "price": { "type": "scaled_float", "scaling_factor": 100 },
    "on_sale": { "type": "boolean" },
    "rating": { "type": "float" },
    "sold_count": { "type": "integer" },
    "review_count": { "type": "integer" },
    "skus": {
      "type": "nested",
      "properties": {
        "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, 
        "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" },
        "price": { "type": "scaled_float", "scaling_factor": 100 }
      }
    },
    "properties": {
      "type": "nested",
      "properties": {
        "name": { "type": "keyword" }, 
        "value": { "type": "keyword" },
        "search_value": { "type": "keyword" }
      }
    }
  }
}


这是ES的原生命令，可以参考下。
还需要配置一下同义词过滤器
| |
黄彦铭
|
|
邮箱：13528685024@163.com
|

签名由 网易邮箱大师 定制

在2020年06月18日 15:46，HuYang 写道：

你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

{
"name" : "g6zRt-N",
"cluster_name" : "elasticsearch_huyang",
"cluster_uuid" : "dvOrOpJXTlqGZ4-OLcajWg",
"version" : {
"number" : "6.8.7",
"build_flavor" : "oss",
"build_type" : "tar",
"build_hash" : "c63e621",
"build_date" : "2020-02-26T14:38:01.193138Z",
"build_snapshot" : false,
"lucene_version" : "7.7.2",
"minimum_wire_compatibility_version" : "5.6.0",
"minimum_index_compatibility_version" : "5.0.0"
},
"tagline" : "You Know, for Search"
}

**Comment by iOShuyang** [comment]
😭幸好找到了这个参考：https://learnku.com/articles/31156

我在里面加上'include_type_name' => false就成功了！！！

**Comment by iOShuyang** [comment]
> 需要7.0以上的版本，因为7.0去除了type的概念，你使用6.8的需要手动设置type，所以代码会报错。 在 2020-06-18 15:36:09，"HuYang" <notifications@github.com> 写道： 你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 6.8.7的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢你的帮助哈

**Comment by iOShuyang** [comment]
> url :{{esHost}}products/_mapping josn :{ "properties": { "type": { "type": "keyword" } , "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "long_title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "category_id": { "type": "integer" }, "category": { "type": "keyword" }, "category_path": { "type": "keyword" }, "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "price": { "type": "scaled_float", "scaling_factor": 100 }, "on_sale": { "type": "boolean" }, "rating": { "type": "float" }, "sold_count": { "type": "integer" }, "review_count": { "type": "integer" }, "skus": { "type": "nested", "properties": { "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "price": { "type": "scaled_float", "scaling_factor": 100 } } }, "properties": { "type": "nested", "properties": { "name": { "type": "keyword" }, "value": { "type": "keyword" }, "search_value": { "type": "keyword" } } } } } 这是ES的原生命令，可以参考下。 还需要配置一下同义词过滤器 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:46，HuYang 写道： 你的es什么版本 | | 黄彦铭 | | 邮箱：13528685024@163.com | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. { "name" : "g6zRt-N", "cluster_name" : "elasticsearch_huyang", "cluster_uuid" : "dvOrOpJXTlqGZ4-OLcajWg", "version" : { "number" : "6.8.7", "build_flavor" : "oss", "build_type" : "tar", "build_hash" : "c63e621", "build_date" : "2020-02-26T14:38:01.193138Z", "build_snapshot" : false, "lucene_version" : "7.7.2", "minimum_wire_compatibility_version" : "5.6.0", "minimum_index_compatibility_version" : "5.0.0" }, "tagline" : "You Know, for Search" } — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

最后一步的时候出现：

PHP Fatal error:  Swoole\Server::set(): document_root[/hyperf-skeleton] does not exist in /Users/huyang/Desktop/HyperfMall/vendor/hyperf/server/src/Server.php on line 104

Fatal error: Swoole\Server::set(): document_root[/hyperf-skeleton] does not exist in /Users/huyang/Desktop/HyperfMall/vendor/hyperf/server/src/Server.php on line 104


请问要怎么解决啊

**Comment by 869413421** [comment]
> > url :{{esHost}}products/_mapping josn :{ "properties": { "type": { "type": "keyword" } , "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "long_title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "category_id": { "type": "integer" }, "category": { "type": "keyword" }, "category_path": { "type": "keyword" }, "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "price": { "type": "scaled_float", "scaling_factor": 100 }, "on_sale": { "type": "boolean" }, "rating": { "type": "float" }, "sold_count": { "type": "integer" }, "review_count": { "type": "integer" }, "skus": { "type": "nested", "properties": { "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "price": { "type": "scaled_float", "scaling_factor": 100 } } }, "properties": { "type": "nested", "properties": { "name": { "type": "keyword" }, "value": { "type": "keyword" }, "search_value": { "type": "keyword" } } } } } 这是ES的原生命令，可以参考下。 还需要配置一下同义词过滤器 | | 黄彦铭 | | 邮箱：[13528685024@163.com](mailto:13528685024@163.com) | 签名由 网易邮箱大师 定制 在2020年06月18日 15:46，HuYang 写道： 你的es什么版本 | | 黄彦铭 | | 邮箱：[13528685024@163.com](mailto:13528685024@163.com) | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. { "name" : "g6zRt-N", "cluster_name" : "elasticsearch_huyang", "cluster_uuid" : "dvOrOpJXTlqGZ4-OLcajWg", "version" : { "number" : "6.8.7", "build_flavor" : "oss", "build_type" : "tar", "build_hash" : "c63e621", "build_date" : "2020-02-26T14:38:01.193138Z", "build_snapshot" : false, "lucene_version" : "7.7.2", "minimum_wire_compatibility_version" : "5.6.0", "minimum_index_compatibility_version" : "5.0.0" }, "tagline" : "You Know, for Search" } — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 最后一步的时候出现：
> 
> PHP Fatal error: Swoole\Server::set(): document_root[/hyperf-skeleton] does not exist in /Users/huyang/Desktop/HyperfMall/vendor/hyperf/server/src/Server.php on line 104
> 
> Fatal error: Swoole\Server::set(): document_root[/hyperf-skeleton] does not exist in /Users/huyang/Desktop/HyperfMall/vendor/hyperf/server/src/Server.php on line 104
> 
> 请问要怎么解决啊

![image](https://user-images.githubusercontent.com/34049702/85086921-9c500e80-b20e-11ea-8403-443388286a4c.png)

**Comment by 869413421** [comment]
> does

在sever配置里面设置自己的静态文件存放目录，这里我写死了忘记调整。

**Comment by 869413421** [comment]
> > > url :{{esHost}}products/_mapping josn :{ "properties": { "type": { "type": "keyword" } , "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "long_title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "category_id": { "type": "integer" }, "category": { "type": "keyword" }, "category_path": { "type": "keyword" }, "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "price": { "type": "scaled_float", "scaling_factor": 100 }, "on_sale": { "type": "boolean" }, "rating": { "type": "float" }, "sold_count": { "type": "integer" }, "review_count": { "type": "integer" }, "skus": { "type": "nested", "properties": { "title": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "description": { "type": "text", "analyzer": "ik_smart", "search_analyzer": "ik_smart_synonym" }, "price": { "type": "scaled_float", "scaling_factor": 100 } } }, "properties": { "type": "nested", "properties": { "name": { "type": "keyword" }, "value": { "type": "keyword" }, "search_value": { "type": "keyword" } } } } } 这是ES的原生命令，可以参考下。 还需要配置一下同义词过滤器 | | 黄彦铭 | | 邮箱：[13528685024@163.com](mailto:13528685024@163.com) | 签名由 网易邮箱大师 定制 在2020年06月18日 15:46，HuYang 写道： 你的es什么版本 | | 黄彦铭 | | 邮箱：[13528685024@163.com](mailto:13528685024@163.com) | 签名由 网易邮箱大师 定制 在2020年06月18日 15:31，HuYang 写道： 正在处理索引 products 索引不存在，准备创建 PHP Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Expected map for property [fields] on field [type] but got a class java.lang.String","caused_by":{"type":"mapper_parsing_exception","reason":"Expected map for property [fields] on field [type] but got a class java.lang.String"}},"status":400} in /Users/huyang/Desktop/HyperfMall/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. { "name" : "g6zRt-N", "cluster_name" : "elasticsearch_huyang", "cluster_uuid" : "dvOrOpJXTlqGZ4-OLcajWg", "version" : { "number" : "6.8.7", "build_flavor" : "oss", "build_type" : "tar", "build_hash" : "c63e621", "build_date" : "2020-02-26T14:38:01.193138Z", "build_snapshot" : false, "lucene_version" : "7.7.2", "minimum_wire_compatibility_version" : "5.6.0", "minimum_index_compatibility_version" : "5.0.0" }, "tagline" : "You Know, for Search" } — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 最后一步的时候出现：
> > PHP Fatal error: Swoole\Server::set(): document_root[/hyperf-skeleton] does not exist in /Users/huyang/Desktop/HyperfMall/vendor/hyperf/server/src/Server.php on line 104
> > Fatal error: Swoole\Server::set(): document_root[/hyperf-skeleton] does not exist in /Users/huyang/Desktop/HyperfMall/vendor/hyperf/server/src/Server.php on line 104
> > 请问要怎么解决啊
> 
> ![image](https://user-images.githubusercontent.com/34049702/85086921-9c500e80-b20e-11ea-8403-443388286a4c.png)

![image](https://user-images.githubusercontent.com/34049702/85087214-76773980-b20f-11ea-8ac7-cf7b6e61b368.png)
